### ISSUE TITLE
`bam2fastq`

### ISSUE THREAD

**Issue by GallVp** [angelovangel/nextflow-fastp#9]
Hi @angelovangel 

Do you have any plans for inclusion of [pbtk/bam2fastq](https://github.com/PacificBiosciences/pbtk) in your workflow?

I am planning to fork your repo and add pbtk/bam2fastq. I thought I should ask you if you already have any such plans? Secondly, are you open to the use of nf-core DSL2 modules in your pipeline?

Cheers

**Comment by angelovangel** [comment]
Hi,
Thanks for the interest in this pipeline. I am not currently maintaining it, but you can go ahead and include the pb tools, it makes certainly sense to work with bam files too.

Best,

Angel

**Comment by GallVp** [comment]
Thank you @angelovangel
